Command line interaction
CentOS/duffy pull request #59
Opened 2021-10-26 08:10 UTC by gridhead

# Viewing CLI usage

```
python3 duffy/app/main.py --help
```

```
Usage: main.py [OPTIONS]

  Duffy is the middle layer running ci.centos.org that manages the
  provisioning, maintenance and teardown / rebuild of the Nodes (physical
  hardware for now, VMs coming soon) that are used to run the tests in the CI
  Cluster. 

Options:
  -p, --portnumb TEXT             Set the port value [0-65536]
  -6, --ipprotv6                  Start the server on an IPv6 address
  -4, --ipprotv4                  Start the server on an IPv4 address
  -l, --loglevel [critical|error|warning|info|debug|trace|info]
                                  Set the log level
  --version                       Show the version and exit.
  --help                          Show this message and exit.
```

# Starting the server at port 8080 using IP version 4 and setting the log level to `warning`

```
python3 duffy/app/main.py -p 9696 -4 -l warning
```

```
 * Starting Duffy...
 * Port number : 9696
 * IP version  : 4
 * Log level   : warning
```

Exit out of the server using `Ctrl` + `C`

Fixes #55

2021-10-26 13:04 UTC, nphilipp requested changes
Apart from the inline comments, the new code needs tests. :wink:

2021-10-26 13:04 UTC, nphilipp commented on duffy/app/__init__.py
> +__version__ = "3.0.0"
We already have that in `duffy.version.__version__` :smiley:

2021-10-26 13:04 UTC, nphilipp commented on duffy/app/main.py
> +from duffy.app import __version__
See above, and use relative imports:

```
…
from fastapi import FastAPI

from ..version import __version__
…
```

2021-10-26 13:04 UTC, nphilipp commented on duffy/app/main.py
> +    mainfunc()
I'd like to have the CLI code in its own module, e.g. `duffy/app/cli.py`. I guess we'll add more initialization code and then `app.py` will soon get very crowded.

2021-10-26 13:04 UTC, nphilipp commented on duffy/app/main.py
> +def mainfunc(portnumb, netprotc, loglevel):
Let's simply call this `main`. This seems to be the consensus on what people call 'main' functions.

2021-10-26 13:04 UTC, nphilipp commented on duffy/app/main.py
> +        netpdata = "0.0.0.0"
The values `netprotc` is compared with don't match up with what's defined for the click options above (`ipprotv6` vs `ipv6` and `ipprotv4` vs `ipv4`).

2021-10-26 13:04 UTC, nphilipp commented on duffy/app/main.py
> +    of the Nodes (physical hardware for now, VMs coming soon) that are used to run the tests in the CI Cluster.
These lines are too long. We limit code lines to 100 characters, but docstrings and long comments should be limited to 72 (see https://www.python.org/dev/peps/pep-0008/#maximum-line-length). Also, let's drop the parentheses, this is just detail which we'll have to update :wink:.

2021-10-26 13:04 UTC, nphilipp commented on duffy/app/main.py
> +@click.option("-p", "--portnumb", "portnumb", help="Set the port value [0-65536]", default="8080")
This option should be an integer, otherwise `uvicorn.run()` will fail:

````
(duffy) nils@makake:~/src/fedora-infra/duffy (cli)> python duffy/app/main.py 
 * Starting Duffy...
 * Port number : 8080
 * IP version  : 4
 * Log level   : info
INFO:     Started server process [100622]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/lib64/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not str
Call stack:
  File "/home/nils/src/fedora-infra/duffy/duffy/app/main.py", line 82, in <module>
    mainfunc()
  File "/home/nils/.virtualenvs/duffy/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/nils/.virtualenvs/duffy/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/nils/.virtualenvs/duffy/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nils/.virtualenvs/duffy/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/nils/src/fedora-infra/duffy/duffy/app/main.py", line 78, in mainfunc
    uvicorn.run("main:app", host=netpdata, port=portnumb, log_level=loglevel)
  File "/home/nils/.virtualenvs/duffy/lib/python3.9/site-packages/uvicorn/main.py", line 447, in run
    server.run()
  File "/home/nils/.virtualenvs/duffy/lib/python3.9/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/usr/lib64/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/nils/.virtualenvs/duffy/lib/python3.9/site-packages/uvicorn/server.py", line 86, in serve
    await self.startup(sockets=sockets)
  File "/home/nils/.virtualenvs/duffy/lib/python3.9/site-packages/uvicorn/server.py", line 176, in startup
    self._log_started_message(listeners)
  File "/home/nils/.virtualenvs/duffy/lib/python3.9/site-packages/uvicorn/server.py", line 217, in _log_started_message
    logger.info(
Message: 'Uvicorn running on %s://%s:%d (Press CTRL+C to quit)'
Arguments: ('http', '0.0.0.0', '8080')
^CINFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [100622]
````

2021-10-26 13:04 UTC, nphilipp commented on README.md
> +* Activate the virtual environment `source venv/bin/activate`.
I think we should document this agnostic of the way a virtualenv is set up, it would work with a poetry-managed one, a classic venv like this one, or one managed by virtualenvwrapper. We can mention the options in one place and that everything needs to happen with it activated, and how it's done, but otherwise users can do what they want.

2021-10-26 13:04 UTC, nphilipp commented on README.md
> +python3 duffy/app/main.py --help
Calling a module from within a package won't work unless we disallow relative imports in it (see below). We should add a console script that executes the main function instead, see https://python-poetry.org/docs/pyproject/#scripts

2021-10-26 13:04 UTC, nphilipp commented on duffy/app/main.py
> +    uvicorn.run("main:app", host="::", port=5000, log_level="info")
What's this function for? I don't see that it's used anywhere.

2021-10-26 13:04 UTC, nphilipp commented on duffy/app/main.py
> +        ["critical", "error", "warning", "info", "debug", "trace", "info"], case_sensitive=False
This contains `info` twice. We could just use the `uvicorn.config.LOG_LEVELS` directly.

2021-10-27 02:40 UTC, gridhead commented on duffy/app/main.py
> +from duffy.app import __version__
I'd suggest the use of absolute imports as we are having the contributors set up Duffy anyway with the use of `poetry install`. Hence, `from duffy.version import __version__` would work just right. What do you say?

2021-10-27 02:42 UTC, gridhead commented on duffy/app/main.py
> +def mainfunc(portnumb, netprotc, loglevel):
[There goes our legacy `Uptownfunc`!](https://github.com/CentOS/duffy/blob/stale/develop/src/duffy/main.py#L37) (Not a rickroll)

2021-10-27 02:50 UTC, gridhead commented on duffy/app/main.py
> +    of the Nodes (physical hardware for now, VMs coming soon) that are used to run the tests in the CI Cluster.
`click` seems to take up the docstrings of the main function (or the entrypoint function) and add it to the help flag automatically. I sought to take advantage of that feature and hence included it. Here's an example.

```
(venv) [t0xic0der@fedorable app]$ python3 cli.py --help
```
```
Usage: cli.py [OPTIONS]

  Duffy is the middle layer running ci.centos.org that manages the
  provisioning, maintenance and teardown / rebuild of the Nodes (physical
  hardware for now, VMs coming soon) that are used to run the tests in the CI
  Cluster.

Options:
  -p, --portnumb TEXT             Set the port value [0-65536]
  -6, --ipv6                      Start the server on an IPv6 address
  -4, --ipv4                      Start the server on an IPv4 address
  -l, --loglevel [critical|error|warning|info|debug|trace|info]
                                  Set the log level
  --version                       Show the version and exit.
  --help                          Show this message and exit.
```

2021-10-27 03:42 UTC, gridhead commented on README.md
> +python3 duffy/app/main.py --help
More of a reason why I specified this https://github.com/CentOS/duffy/pull/59#discussion_r737058980

2021-10-27 04:03 UTC, gridhead commented on duffy/app/__init__.py
> +__version__ = "3.0.0"
Addressed https://github.com/CentOS/duffy/pull/59/commits/5a271bd93741f6a6b70885ee4697592866b17cec

2021-10-27 04:04 UTC, gridhead commented on duffy/app/main.py
> +from duffy.app import __version__
Addressed https://github.com/CentOS/duffy/pull/59/commits/5a271bd93741f6a6b70885ee4697592866b17cec

2021-10-27 04:04 UTC, gridhead commented on duffy/app/main.py
> +    mainfunc()
Addressed https://github.com/CentOS/duffy/pull/59/commits/b7fcee7011c8f3f18afab62c03b04cadc882e366

2021-10-27 04:05 UTC, gridhead commented on duffy/app/main.py
> +def mainfunc(portnumb, netprotc, loglevel):
Addressed https://github.com/CentOS/duffy/pull/59/commits/b7fcee7011c8f3f18afab62c03b04cadc882e366

2021-10-27 04:05 UTC, gridhead commented on duffy/app/main.py
> +        netpdata = "0.0.0.0"
Addressed https://github.com/CentOS/duffy/pull/59/commits/9627ca5acc7928880cd675f5e3c38fb094dbe3e7

2021-10-27 04:06 UTC, gridhead commented on duffy/app/main.py
> +    of the Nodes (physical hardware for now, VMs coming soon) that are used to run the tests in the CI Cluster.
Addressed https://github.com/CentOS/duffy/pull/59/commits/d4f90920c93071037ca6daf9d4b95febe17216e7

2021-10-27 04:06 UTC, gridhead commented on duffy/app/main.py
> +@click.option("-p", "--portnumb", "portnumb", help="Set the port value [0-65536]", default="8080")
Addressed https://github.com/CentOS/duffy/pull/59/commits/0791cc10659eef77aeb0c62c30a183c40294b0c3

2021-10-27 04:07 UTC, gridhead commented on README.md
> +* Activate the virtual environment `source venv/bin/activate`.
Addressed https://github.com/CentOS/duffy/pull/59/commits/b8bd898faeb6d857a7177c685de6dfcd135d5927

2021-10-27 04:07 UTC, gridhead commented on README.md
> +python3 duffy/app/main.py --help
Addressed https://github.com/CentOS/duffy/pull/59/commits/35f2ab801c4d87bc17c24435cb3b585162317a3e

2021-10-27 04:07 UTC, gridhead commented on duffy/app/main.py
> +    uvicorn.run("main:app", host="::", port=5000, log_level="info")
Addressed https://github.com/CentOS/duffy/pull/59/commits/b7fcee7011c8f3f18afab62c03b04cadc882e366

2021-10-27 04:07 UTC, gridhead commented on duffy/app/main.py
> +        ["critical", "error", "warning", "info", "debug", "trace", "info"], case_sensitive=False
Addressed https://github.com/CentOS/duffy/pull/59/commits/f14e86d6f15ae00efabc7dd5cd4e4cee666a6cd0

2021-10-27 10:41 UTC, nphilipp approved these changes
Looks good to me!

2021-10-27 10:41 UTC, merged